-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggFwPhKuRLSE9WNNv
RudwYPaS4Q1dgeBagsXYdwrJD2CgCgYIKoZIzj0DAQehRANCAAStOtjwz61chobh
80qlamOldyGG9Nd7QEncosWVnfYSpYszM44AnSEr9jKLBXWwRd4cKk1ckbgrCowc
dlTOf4SF
-----END PRIVATE KEY-----